---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ublue-kinoite-custom
description: ~kinoite-main~ bazzite + some packages for my convenience

base-image: ghcr.io/ublue-os/bazzite
image-version: 42 # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    repos:
      # copr:
      #  - matinlotfali/KDE-Rounded-Corners
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://repo.librewolf.net/librewolf.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      packages:
        - fish
        - konsole
        - mullvad-vpn
        - kbct
    remove:
      packages:
        - ptyxis

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - kbct.service
        - kbct-restart.service

  - type: signing
