---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ublue-kinoite-custom
description: kinoite-main + some packages for my convenience

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    install:
      packages:
        - fish
        - steam
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://repo.librewolf.net/librewolf.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

